GET http://localhost:3000/products

###
GET http://localhost:3000/products/1

###
GET http://localhost:3000/products/10

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "productId": 6,
    "productName": "abcd",
    "productCode": "GMG-0042",
    "releaseDate": "October 15, 2015",
    "description": "Standard two-button video game controller",
    "price": 100,
    "starRating": 4.5,
    "imageUrl": "http://openclipart.org/image/300px/svg_to_png/120337/xbox-controller_01.png"
}

###
PUT http://localhost:3000/products/60
Content-Type: application/json

{
    "productId": 0,
    "productName": "abcd",
    "productCode": "GMG-0042",
    "releaseDate": "October 15, 2015",
    "description": "Standard two-button video game controller",
    "price": 200,
    "starRating":3.5,
    "imageUrl": "http://openclipart.org/image/300px/svg_to_png/120337/xbox-controller_01.png"
}

###
DELETE http://localhost:3000/products/6